# version: "3"
# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5601:5601"
#     restart: always
version: "3"
services:
  api:
    build:
      context: .
    ports:
      - "55555:55555"
    volumes:
      - .:/usr/app/src
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: ["/bin/bash", "-c", "/usr/app/src/startup.sh"] # Đảm bảo /bin/bash chạy đúng lệnh
